k3s_version: "v1.32.4+k3s1"
k3s_node_ip: "{{ ansible_host }}"
k3s_extra_server_args: "--disable traefik"
k3s_token_path: "{{ lookup('env', 'HOME') }}/.local/share/k3s-token"
k3s_kubeconfig_dest: "{{ lookup('env', 'HOME') }}/.kube/config"
