Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_check_update = false

  # Uncomment and drop your public key at dev/.local/ssh.pub to automate Ansible access
  # config.vm.provision "shell" do |s|
  #   s.inline = "cat /vagrant/.local/ssh.pub >> /home/vagrant/.ssh/authorized_keys"
  # end

  config.vm.define "k3s-master" do |master|
    master.vm.hostname = "k3s-master"
    master.vm.network "private_network", ip: "192.168.56.101"
    master.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-master"
      vb.memory = 4096
      vb.cpus   = 2
    end
  end

  config.vm.define "k3s-worker" do |worker|
    worker.vm.hostname = "k3s-worker"
    worker.vm.network "private_network", ip: "192.168.56.102"
    worker.vm.provider "virtualbox" do |vb|
      vb.name   = "k3s-worker"
      vb.memory = 4096
      vb.cpus   = 2
    end
  end
end
