
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"


  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      # Basic packages
      apt-get update -qq
      apt-get install -y -qq curl wget git htop
    SHELL
  end

  config.vm.define "k3s-master" do |master|
      master.vm.hostname = "k3s.master"
      master.vm.network "private_network", ip: "192.168.56.101"
      master.vm.provider 'VirtualBox' do |vb|
         vb.memory = '4096'
         vb.cpu = 2
      end
  end

  config.vm.define "k3s-worker-1" do |worker|
      worker.vm.hostname = "k3s.worker1"
      worker.vm.network "private_network", ip: "192.168.56.102"
      worker.vm.provider 'VirtualBox' do |vb|
         vb.memory = '4096'
         vb.cpu = 2
      end
  end
end
